### ISSUE TITLE
希望去掉默认的配置

### ISSUE THREAD

**Issue by 21paradox** [dlutwuwei/grunt-tmodjs#1]
var options = {
            output: this.options().output || './build',
            charset: this.options().charset || 'utf-8',
            debug: this.options().debug || false, // 此字段不会保存在配置中
            watch: this.options().watch || false,
            type: this.options().type || "templatejs",
            syntax: this.options().syntax || "native",
            helpers: this.options().helpers,
            escape: this.options().escape,
            compress: this.options().compress || true,
            runtime: this.options().runtime || "template.js",
            combo: this.options().combo || true,
            minify: this.options().minify || true,
            cache: this.options().cache || true
        };

我想让 combo 变成 false, 如果在我的 grunt options 里配置 combo为 false,
this.options().combo || true, 这句话会让我的配置失效。

**Comment by dlutwuwei** [comment]
fix it

**Comment by 21paradox** [comment]
3q
